### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by IfzaRasool** [VTY1999/Conference-page#2]
**You are doing a Good Job** 

- All linters are Passed.
- Documented Good Readme file
- If you Apply Hover on the cards of the main program section so looks good.

**Comment by BereketRetta** [comment]
Great Job! 
--Excellent Readme file
-- All Javascript, HTML/CSS linters have Passed.

**Comment by VTY1999** [comment]
Thank you for your feedback everyone.
